### ISSUE TITLE
Theme color for placeholder is not working

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/textarea#11]
## Theme
- [x] Placeholder color is not working in valid state
http://localhost:8080/?path=/story/textarea-ui--react-theme-all-states

**Comment by Kosukeee** [comment]
Fixed valid state placeholder theme,
https://github.com/rakuten-rex/textarea/commit/1af51c062a2838f2f0caf823194722d52a2893ef

**Comment by claudio-moya** [comment]
thanx
