### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/textarea#2]
Component
- [x] Border radius is bigger than figma file, it should be 4px -> 0.25rem
- [x] Add missed styles for `focus`, `active` and match the colors with figma (border, font color, placeholder, margins, etc.)
- [x] Create a className for `focus`, `active`, `hover` state to test the values
- [x] Active state for Helper UI is not blue, confirm with figma file and designers
- [x] Fix console warnings, example http://localhost:8080/?path=/story/textarealabel--with-dynamic-props
![Screen Shot 2020-02-03 at 3 38 03 PM](https://user-images.githubusercontent.com/10554673/73631076-45043400-469b-11ea-82f9-90a8ba153a69.png)

Theme
- [x] Add missed styles for `focus`, `active`, `hover` states
- [x] Add Placeholder color for `focus`, `active`, `hover` states

Stories
- [x] Create stories for className to test `focus`, `active`, `hover` state
- [x] Add stories `with Icon` in Helper UI and Label UI for different states

**Comment by claudio-moya** [comment]
Component
- [ ]  Change classNames to:
- rex-textarea
  - rex-textarea-label
  - rex-textarea-ui
  - rex-textarea-helper

**Comment by claudio-moya** [comment]
Component
- [ ] Add missed prop for `default text`, currently only `placeholder` can be set as property in Knobs

Stories
- [ ] Knobs properties are not working: Rows, Cols, maxLength, minLength

Theme
- [ ] `Focused Border Color` is not working
- [ ] Sort, rename and add Theme options like this:

Border Color -> Normal State Border
Label Text Color -> Normal State Label
Helper Text Color -> Normal State Helper
Placeholder Text Color -> Normal State Placeholder
Text Color -> Normal State Text

(new)-> Hover State Border
(new) -> Hover State Label
(new) -> Hover State Helper
(new) -> Hover State Placeholder
(new) -> Hover State Text

Focused Border Color -> Active State Border
(new) -> Active State Label
(new) -> Active State Helper
(new) -> Active State Placeholder
(new) -> Active State Text

**Comment by claudio-moya** [comment]
Component
- [ ] The border style for 2px on hover/active state is moving the input field and the elements, try a new way to avoid that change:

On`textarea` hover/active state, change `border` and `background color` of `rex-textarea-wrapper`
to simulate that the border changed from 1px to 2px.

```html
<div class="rex-textarea-wrapper" style="
    border-style: solid;
    border-width: 1px;
    border-color: transparent;
    border-radius: 0.25rem;
    padding: 0;
    background-color: transparent;
">
<textarea id="age" class="rex-textarea-ui" name="" placeholder="Placeholder" aria-labelledby="labelId"></textarea>
</div>
```

```css
.rex-textarea-ui:focus, .rex-textarea-ui.focus {
...
border-width: 1px; // current value is border-width: 2px;
}
```

**Comment by claudio-moya** [comment]
Theme
- Create new categories (Knobs tabs) for the theme colors: Theme Normal, Theme Hover, Theme Focus, Theme Active, Theme Error, Theme Disabled, etc
- Add components examples to see the changes on the states (normal, active, focus, hover, error, valid, disabled) in one story, example: 
```jsx
<TextareaLabelHelper style={{
    "--rex-textarea-border-color": "crimson",
   ...
  }} 
placeholder='Normal State' .../>

<TextareaLabelHelper style={{
    "--rex-textarea-border-color": "crimson",
   ...
  }} 
placeholder='Active State'  state='active' ... />

<TextareaLabelHelper style={{
    "--rex-textarea-border-color": "crimson",
   ...
  }} 
placeholder='Active State'  state='valid' ... />

<TextareaLabelHelper style={{
    "--rex-textarea-border-color": "crimson",
   ...
  }} 
placeholder='Active State'  state='error' ... />

<TextareaLabelHelper style={{
    "--rex-textarea-border-color": "crimson",
   ...
  }} 
placeholder='Active State' disabled={true} ... />
```

**Comment by claudio-moya** [comment]
Theme
- [ ] Remove Theme props for Helper Font Size, due to icon size is not matching the change and is not critical feature

**Comment by claudio-moya** [comment]
Component
- [ ] Fix build warnings:
```
ERROR in ./src/TextareaHelper/TextareaHelper.jsx
    Module Error (from ./node_modules/eslint-loader/dist/cjs.js):
    
    /Users/claudio.moya/Develop/project/rakuten-rex/textarea/src/TextareaHelper/TextareaHelper.jsx
      27:5  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
      30:5  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
      35:7  error  onMouseOver must be accompanied by onFocus for accessibility           jsx-a11y/mouse-events-have-key-events
      35:7  error  onMouseOut must be accompanied by onBlur for accessibility             jsx-a11y/mouse-events-have-key-events
```

**Comment by Kosukeee** [comment]
- [ ] Separate  `Active` and `Focus` state theme colors knobs

**Comment by claudio-moya** [comment]
Component
- [ ] Set `height: 4.75rem` and `min-height: 4.75rem` to `textarea` tag (default height looks different between Chrome, Safari and Firefox)

**Comment by claudio-moya** [comment]
Component
- [ ] Remove dependency of rex-icons, use specific SVG icon instead

src/HelperUi/HelperUi.jsx
```jsx
import Icon from '@rakuten-rex/icons/embedded';
```
